services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:80"
  database:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: le_menhir_des_dieux
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8081:80"
